CREATE TABLE cliente (
    idcliente   NUMBER PRIMARY KEY,
    nombre    NVARCHAR2(15),
    telefono NUMBER(10),
    direccion NVARCHAR2(50)
    --CONSTRAINT check_continente_p CHECK ( continente_p IN ( 'AMERICA', 'AFRICA', 'EUROPA', 'ASIA', 'OCEANIA' ) ),
    --idpresidentes NUMBER(3)
);

CREATE TABLE auto(
    idauto NUMBER PRIMARY KEY,
    modelo        NVARCHAR2(20),
    marca         NVARCHAR2(20),
    placas         NVARCHAR2(20)
);

CREATE TABLE renta(
    idrenta NUMBER PRIMARY KEY,
    fecha_ini    DATE,
    fecha_fin    DATE,
    costo_ren NUMBER(5),
    idcliente NUMBER(3),
    idauto NUMBER(3)
);

--CREAR LLAVE FORANEA
ALTER TABLE renta
    ADD CONSTRAINT fkidcliente FOREIGN KEY ( idcliente )
        REFERENCES cliente ( idcliente );

ALTER TABLE renta
    ADD CONSTRAINT fkidauto FOREIGN KEY ( idauto )
        REFERENCES auto ( idauto );



Describe cliente;
Describe auto;
Describe renta;
select * from cliente;
select * from auto;
select * from renta;

CREATE SEQUENCE CLIENTE_SEQ;
CREATE SEQUENCE AUTO_SEQ;
CREATE SEQUENCE RENTA_SEQ;

CREATE OR REPLACE TRIGGER ON_INSERT_cliente BEFORE
INSERT ON cliente FOR EACH ROW BEGIN
SELECT cliente_SEQ.NEXTVAL INTO :new.idcliente FROM dual;
END;

CREATE OR REPLACE TRIGGER ON_INSERT_auto BEFORE
INSERT ON auto FOR EACH ROW BEGIN
SELECT auto_SEQ.NEXTVAL INTO :new.idauto FROM dual;
END;

CREATE OR REPLACE TRIGGER ON_INSERT_renta BEFORE
INSERT ON renta FOR EACH ROW BEGIN
SELECT renta_SEQ.NEXTVAL INTO :new.idrenta FROM dual;
END;

INSERT ALL
INTO cliente(NOMBRE,TELEFONO,DIRECCION)
VALUES('José','4751035696','Hidalgo #730')
INTO cliente(NOMBRE,TELEFONO,DIRECCION)
VALUES('Edgar','4161035696','Blvd #1550')
INTO cliente(NOMBRE,TELEFONO,DIRECCION)
VALUES('Ramiro','6461076664','Hermenegildo Galeana #126')
SELECT * FROM DUAL;

INSERT ALL
INTO auto(MODELO,MARCA,PLACAS)
VALUES('FRONTIER V6 PRO-4X','NISSAN','3RF4TG6')
INTO auto(MODELO,MARCA,PLACAS)
VALUES('ACCENT SD 2022','HYUNDAY','D234D34')
INTO auto(MODELO,MARCA,PLACAS)
VALUES('EXPEDITION 2022','FORD','FK23S24D')
SELECT * FROM DUAL;

INSERT ALL
INTO renta(FECHA_INI,FECHA_FIN,COSTO_REN,IDCLIENTE,IDAUTO)
VALUES('12/01/2021','21/06/2021',6000,1,2)
INTO renta(FECHA_INI,FECHA_FIN,COSTO_REN,IDCLIENTE,IDAUTO)
VALUES('12/06/2019','21/12/2022',8003,1,2)
INTO renta(FECHA_INI,FECHA_FIN,COSTO_REN,IDCLIENTE,IDAUTO)
VALUES('12/07/2018','21/11/2022',7500,2,1)
INTO renta(FECHA_INI,FECHA_FIN,COSTO_REN,IDCLIENTE,IDAUTO)
VALUES('12/04/2020','21/04/2021',1200,3,1)
INTO renta(FECHA_INI,FECHA_FIN,COSTO_REN,IDCLIENTE,IDAUTO)
VALUES('12/03/2019','21/07/2020',3200,2,3)
SELECT * FROM DUAL;
    
ALTER TABLE auto ADD CONSTRAINT placas UNIQUE ( placas );

--UPDATE PAISES SET NOMBRE = 'México' Where NOMBRE = 'PEÑANIETO';
