CREATE TABLE empleado (
    empleado_id  NUMBER PRIMARY KEY,
    nombre       NVARCHAR2(15),
    antiguedad   NUMBER,
    sexo         CHAR(1),
    estado_civil NVARCHAR2(10),
    fecha_nac    DATE,
    cargo_id     NUMBER,
    status       NUMBER,
    CONSTRAINT check_sexo CHECK ( sexo IN ( 'M', 'F' ) ),
    CONSTRAINT check_estado_civil CHECK ( estado_civil IN ( 'SOLTERO', 'CASADO', 'VIUDO', 'DIVORCIADO' ) )
);

CREATE TABLE cargo (
    cargo_id    NUMBER PRIMARY KEY,
    descripcion NVARCHAR2(20),
    antiguedad  NUMBER(5, 2)
);

--CREAR LLAVE FORANEA
ALTER TABLE empleado ADD CONSTRAINT EMP_FK_CARGO_ID
FOREIGN KEY(cargo_id)
REFERENCES CARGO(cargo_id);

Describe cargo;

INSERT INTO cargo VALUES(1,'CEO',999.99);
INSERT INTO cargo VALUES(2,'GERENTmE',990.99);
INSERT INTO cargo VALUES(3,'ADMINISTRADOR',900.99);
INSERT INTO cargo VALUES(4,'LIDER TECNICO',850.99);
INSERT INTO cargo VALUES(5,'SCRUM MASTER',800.99);
INSERT INTO cargo VALUES(6,'DESARROLLADOR',995.99);

select * from cargo;

CREATE SEQUENCE CARGO_SEQ;


CREATE OR REPLACE TRIGGER ON_INSERT_CARGO BEFORE
INSERT ON CARGO FOR EACH ROW BEGIN
SELECT CARGO_SEQ.NEXTVAL INTO :new.CARGO_ID FROM dual;
END;

INSERT ALL
INTO CARGO(DESCRIPCION,SUELDO)
VALUES('AUXILIAR',400.50)
INTO CARGO (DESCRIPCION,SUELDO)
VALUES('AUXILIAR',400.50)
INTO CARGO (DESCRIPCION,SUELDO)
VALUES('AUXILIAR',400.50)
SELECT * FROM DUAL;







Describe empleado;

INSERT INTO empleado VALUES(1,'Juan','12/04/2022','M','SOLTERO','12/04/2022',3,1);
INSERT INTO empleado VALUES(2,'German','13/05/2022','M','CASADO','15/08/2022',3,2);
INSERT INTO empleado VALUES(3,'Javier','14/06/2022','M','VIUDO','16/09/2022',1,1);

select * from empleado;

CREATE SEQUENCE EMPLEADO_SEQ;

CREATE OR REPLACE TRIGGER ON_INSERT_EMPLEADO BEFORE
INSERT ON EMPLEADO FOR EACH ROW BEGIN
SELECT EMPLEADO_SEQ.NEXTVAL INTO :new.EMPLEADO_ID FROM dual;
END;

INSERT ALL
INTO EMPLEADO(NOMBRE,ANTIGUEDAD,SEXO,ESTADO_CIVIL,FECHA_NAC,CARGO_ID,STATUS)
VALUES('Javier','14/06/2022','M','VIUDO','16/09/2022',1,1)
INTO EMPLEADO(NOMBRE,ANTIGUEDAD,SEXO,ESTADO_CIVIL,FECHA_NAC,CARGO_ID,STATUS)
VALUES('Juana','08/03/2021','F','VIUDO','03/08/2022',2,1)
SELECT * FROM DUAL;

